
export const institutions = [
    {id:1, name:"University of the Witwatersrand", location:"Johannesburg, Gauteng",
     image: "img/wits.jpg", date: "September 30 2022",
      link:"https://self-service.wits.ac.za/psc/csprodonl/UW_SELF_SERVICE/SA/c/VC_OA_LOGIN_MENU.VC_OA_LOGIN_FL.GBL"},
      {id:2,name:"University of Johannesburg", location:"Johannesburg, Gauteng",
     image: "img/uj.jpg", date: "September 30 2022",
      link:"https://registration.uj.ac.za/pls/prodi41/gen.gw1pkg.gw1view"},
      {id:3,name:"University of Pretoria", location:"Gauteng",
     image: "img/up.jpg", date: "June 30 2022",
      link:"https://upnet.up.ac.za/psc/upapply/EMPLOYEE/SA/c/UP_OAP_MENU.UP_OAP_LOGIN_FL.GBL"},
      {id:4,name:"University of KwaZulu-Natal", location:"Durban, Pinetown and Pietermartizburg, KwaZulu-Natal",
     image: "img/ukzn.jpg", date: "September 30 2022",
      link:"https://erpweb.ukzn.ac.za/pls/ukznint/gen.gw1pkg.gw1view"},
      {id:5,name:"Rhodes University", location:"Eastern Cape",
     image: "img/ru.jpg", date: "September 30 2022",
      link:"https://ross.ru.ac.za/"},
      {id:6,name:"University of the Western Cape", location:"Bellville, Western Cape",
     image: "img/uwc.jpg", date: "September 30 2022",
      link:"https://student.uwc.ac.za/"},
      {id:7,name:"Cape Peninsula University of Technology", location:"Bellville, Western Cape",
     image: "img/cput.jpg", date: "30 September 2022",
      link:"https://student.uwc.ac.za/"},
      {id:8,name:"North-West University", location:"North-West and Gauteng",
     image: "img/nwu.jpg", date: "September 30 2022",
      link:"http://distance.nwu.ac.za/apply-online"},
      {id:9,name:"Nelson Mandela University", location:"Eastern Cape and Western Cape",
     image: "img/nmu.PNG", date: "30 June 2022",
      link:"https://applyonline.mandela.ac.za/"}    
]