
export const institutions = [
    {id:1, name:"University of the Witwatersrand", location:"Johannesburg, Gauteng",
     image: "img/wits.jpg", date: "September 30 2022",
      link:"https://self-service.wits.ac.za/psc/csprodonl/UW_SELF_SERVICE/SA/c/VC_OA_LOGIN_MENU.VC_OA_LOGIN_FL.GBL"},
      {id:2,name:"University of Johannesburg", location:"Johannesburg, Gauteng",
     image: "img/uj.jpg", date: "September 30 2022",
      link:"https://registration.uj.ac.za/pls/prodi41/gen.gw1pkg.gw1view"},
      {id:3,name:"University of Pretoria", location:"Gauteng",
     image: "img/up.jpg", date: "June 30 2022",
      link:"https://upnet.up.ac.za/psc/upapply/EMPLOYEE/SA/c/UP_OAP_MENU.UP_OAP_LOGIN_FL.GBL"},
      {id:4,name:"University of KwaZulu-Natal", location:"Durban, Pinetown and Pietermartizburg, KwaZulu-Natal",
     image: "img/ukzn.jpg", date: "September 30 2022",
      link:"https://erpweb.ukzn.ac.za/pls/ukznint/gen.gw1pkg.gw1view"},
      {id:5,name:"Rhodes University", location:"Eastern Cape",
     image: "img/ru.jpg", date: "September 30 2022",
      link:"https://ross.ru.ac.za/"},
      {id:6,name:"University of the Western Cape", location:"Bellville, Western Cape",
     image: "img/uwc.jpg", date: "September 30 2022",
      link:"https://student.uwc.ac.za/"},
      {id:7,name:"Cape Peninsula University of Technology", location:"Bellville, Western Cape",
     image: "img/cput.jpg", date: "30 September 2022",
      link:"https://student.uwc.ac.za/"},
      {id:8,name:"North-West University", location:"North-West and Gauteng",
     image: "img/nwu.jpg", date: "September 30 2022",
      link:"http://distance.nwu.ac.za/apply-online"},
      {id:9,name:"Nelson Mandela University", location:"Eastern Cape and Western Cape",
     image: "img/nmu.png", date: "30 June 2022",
      link:"https://applyonline.mandela.ac.za/"},
      {id:10,name:"Central University of Technology", location:"Free State",
     image: "img/cut.jpg", date: "September 30 2022",
      link:"https://enroll.cut.ac.za/pls/prodi41/w99pkg.mi_login"},
       {id:11,name:"University of the Free State", location:"Free State",
     image: "img/ufs.jpg", date: "September 30 2022",
      link:"https://apply.ufs.ac.za/Application/Start"},
       {id:12,name:"University of Fort Hare", location:"Eastern Cape",
     image: "img/ufh.jpg", date: "31 October 2022",
       link:"https://apply.ufs.ac.za/Application/Start"},
       {id:13,name:"University of Zululand", location:"KwaZulu-Natal",
     image: "img/uoz.jpg", date: "31 October 2022",
       link:"http://www.unizulu.ac.za/apply/"},
       {id:14,name:"University of Mpumalanga", location:"Mpumalanga",
     image: "img/uom.jpg", date: "September 30 2022",
       link:"https://ienabler.ump.ac.za/pls/prodi41/gen.gw1pkg.gw1view"},
       {id:15,name:"Walter Sisulu University", location:"Eastern Cape",
    image: "img/wsu.jpg", date: "September 30 2022",
       link:"https://ieweb.wsu.ac.za/pls/prodi41/gen.gw1pkg.gw1view"},
       {id:16,name:"Durban University of Technology", location:"KwaZulu-Natal",
    image: "img/dut.jpg", date: "September 30 2022",
       link:"www.cao.ac.za"},
       {id:17,name:"Mangosuthu University of Technology", location:"KwaZulu-Natal",
    image: "img/mut.jpg", date: "September 30 2022",
       link:"http://www.cao.ac.za/"},
       {id:18,name:"Sol Plaatjie University", location:"Northern Cape",
    image: "img/spu.jpg", date: "30 November 2022",
       link:"https://www.spu.ac.za/index.php/how-to-apply/"},
       {id:19,name:"Vaal University of Technology", location:"Gauteng, North-West, Mpumulanga and Northern Cape",
    image: "img/vut.jpg", date: "30 September 2022",
       link:"https://ienablerprod.vut.ac.za/pls/prodi41/w99pkg.mi_login"},
       {id:20,name:"University of Limpopo", location:"Limpopo and Gauteng",
    image: "img/uol.jpg", date: "30 September 2022",
       link:"https://ulc-prod-webserver.ul.ac.za/pls/prodi41/gen.gw1pkg.gw1view"},
       {id:21,name:"University of Venda for Science and Technology", location:"Limpopo",
    image: "img/univenda.jpg", date: "31 December 2022",
        link:"https://univenien.univen.ac.za/pls/prodi04/gen.gw1pkg.gw1view"},
        {id:22,name:"Tshwane University of Technology", location:"Gauteng, Mpumalanga, Limpopo and North-West",
    image: "img/tut.jpg", date: "2 September 2022 ",
        link:"https://ienabler.tut.ac.za/pls/prodi41/gen.gw1pkg.gw1view"}             
]